version: '3'
services:
  web:
    build: .
    container_name: mulch-mapper
    restart: always
    volumes:
      - /mnt/user/appdata/MulchMapper:/mulch:rw
    env_file:
      - /mnt/user/appdata/MulchMapper/.env
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    ports:
      - "80:80"
    networks:
      br0:
        ipv4_address: 10.7.10.15

networks:
  br0:
    external: true 